export const GET_EARNINGS = "GET_EARNINGS";
export const GET_DOCTORS = "GET_DOCTORS";
export const GET_STAFFS = "GET_STAFFS";
export const GET_ROOMS = "GET_ROOMS";

export const GET_ALL_DEPARTMENTS = "GET_ALL_DEPARTMENTS";

export const GET_DEPARTMENT_BY_ID = "GET_DEPARTMENT_BY_ID";

export const GET_APPOINTMENTS = "GET_APPOINTMENTS";
export const GET_REQUESTED_APPOINTMENTS = "GET_REQUESTED_APPOINTMENTS";

export const GET_APPOINTMENT_REQUESTS = "GET_APPOINTMENT_REQUESTS";

export const GET_REJECTED_APPOINTMENTS = "GET_REJECTED_APPOINTMENTS";

export const GET_PATIENTS = "GET_PATIENTS";

export const ADD_ROOM = "ADD_ROOM";
export const UPDATE_ROOM = "UPDATE_ROOM";
export const DELETE_ROOM = "DELETE_ROOM";

export const ADD_STAFFS = "ADD_STAFFS";
export const DELETE_STAFFS = "DELETE_STAFFS";
