export const GET_EARNINGS = "GET_EARNINGS";

export const GET_DOCTORS = "GET_DOCTORS";
export const GET_FILTERED_DOCTORS = "GET_FILTERED_DOCTORS";
export const ADD_DOCTORS = "ADD_DOCTORS";
export const DELETE_DOCTORS = "DELETE_DOCTORS";
export const UPDATE_DOCTORS = "UPDATE_DOCTORS";

export const GET_ALL_DEPARTMENTS = "GET_ALL_DEPARTMENTS";

export const GET_DEPARTMENT_BY_ID = "GET_DEPARTMENT_BY_ID";
export const GET_SERVICES_BY_DEPARTMENT_ID = "GET_SERVICES_BY_DEPARTMENT_ID";

export const ADD_DEPARTMENT = "ADD_DEPARTMENT";

export const GET_APPOINTMENTS = "GET_APPOINTMENTS";
export const GET_SCHEDULED_APPOINTMENTS = "GET_SCHEDULED_APPOINTMENTS";
export const GET_ONGOING_APPOINTMENTS = "GET_ONGOING_APPOINTMENTS";
export const GET_WAITING_APPOINTMENTS = "GET_WAITING_APPOINTMENTS";
export const GET_COMPLETED_APPOINTMENTS = "GET_COMPLETED_APPOINTMENTS";

export const GET_APPOINTMENT_REQUESTS = "GET_APPOINTMENT_REQUESTS";

export const GET_REJECTED_APPOINTMENTS = "GET_REJECTED_APPOINTMENTS";

export const GET_PATIENTS = "GET_PATIENTS";

export const GET_FILTERED_PATIENTS = "GET_FILTERED_PATIENTS";

export const GET_ROOMS = "GET_ROOMS";
export const GET_FILTERED_ROOMS = "GET_FILTERED_ROOMS";
export const ADD_ROOM = "ADD_ROOM";
export const UPDATE_ROOM = "UPDATE_ROOM";
export const DELETE_ROOM = "DELETE_ROOM";

export const GET_STAFFS = "GET_STAFFS";
export const ADD_STAFFS = "ADD_STAFFS";
export const DELETE_STAFFS = "DELETE_STAFFS";
export const UPDATE_STAFFS = "UPDATE_STAFFS";

export const GET_EXPENSES = "GET_EXPENSES";
export const ADD_EXPENSE = "ADD_EXPENSE";

export const UPDATE_EXPENSE = "UPDATE_EXPENSE";
export const DELETE_EXPENSE = "DELETE_EXPENSE";

export const GET_BILLING_RECORDS = "GET_BILLING_RECORDS";
export const GET_BILL_DETAILS = "GET_BILL_DETAILS";

export const GET_SERVICES = "GET_SERVICES";

export const ADD_SERVICE = "ADD_SERVICE";

export const GET_APPOINTMENT_COUNTS = "GET_APPOINTMENT_COUNTS";

export const UPDATE_SERVICE = "EDIT_SERVICE";

export const DELETE_SERVICE = "DELETE_SERVICE";
export const GET_ADMISSION_REQUESTS_FOR_APPROVAL =
  "GET_ADMISSION_REQUESTS_FOR_APPROVAL";

export const DELETE_SERVICE_CATEGORY = "DELETE_SERVICE_CATEGORY";
export const GET_DOCTOR_REQUESTS = "GET_DOCTOR_REQUESTS";

export const ACCEPT_REQUEST = "ACCEPT_REQUEST";
export const GET_INSURED_PATIENTS = "GET_INSURED_PATIENTS";
export const EDIT_INSURED_PATIENT = "EDIT_INSURED_PATIENT";
export const UPDATE_STATUS_OF_INSURED_PATIENTS =
  "UPDATE_STATUS_OF_INSURED_PATIENTS";
export const GET_INSURANCE_COMPANIES = "GET_INSURANCE_COMPANIES";
export const ADD_INSURANCE_COMPANY = "ADD_INSURANCE_COMPANY";
export const ADD_SERVICE_TO_COMPANY = "ADD_SERVICE_TO_COMPANY";
export const DELETE_TPA_SERVICE_CATEGORY = "DELETE_TPA_SERVICE_CATEGORY";
export const DELETE_TPA_SERVICE = "DELETE_TPA_SERVICE";
export const EDIT_TPA_SERVICE = "EDIT_TPA_SERVICE";
export const ADD_ESTIMATED_BILL = "ADD_ESTIMATED_BILL";
export const EDIT_ESTIMATED_BILL = "EDIT_ESTIMATED_BILL";
export const GET_ESTIMATED_BILL = "GET_ESTIMATED_BILL";
export const NULL_ESTIMATED_BILL = "NULL_ESTIMATED_BILL";
export const GET_PACKAGES = "GET_PACKAGES";
export const GET_PROGRESS_TRACKER = "GET_PROGRESS_TRACKER";

export const GET_ROOM_TYPES = "GET_ROOM_TYPES";
export const GET_FILTERED_INPATIENTS = "GET_FILTERED_INPATIENTS";

export const GET_ADMISSION_REQUESTS = "GET_ADMISSION_REQUESTS";

export const UPDATE_ADMISSION_INSURANCE = "UPDATE_ADMISSION_INSURANCE";
export const ADD_PAYMENT_TO_BILL = "ADD_PAYMENT_TO_BILL";
