export const GET_EARNINGS = "GET_EARNINGS";

export const GET_DOCTORS = "GET_DOCTORS";
export const ADD_DOCTORS = "ADD_DOCTORS";
export const DELETE_DOCTORS = "DELETE_DOCTORS";
export const UPDATE_DOCTORS = "UPDATE_DOCTORS";

export const GET_ALL_DEPARTMENTS = "GET_ALL_DEPARTMENTS";

export const GET_DEPARTMENT_BY_ID = "GET_DEPARTMENT_BY_ID";

export const GET_APPOINTMENTS = "GET_APPOINTMENTS";
export const GET_REQUESTED_APPOINTMENTS = "GET_REQUESTED_APPOINTMENTS";

export const GET_APPOINTMENT_REQUESTS = "GET_APPOINTMENT_REQUESTS";

export const GET_REJECTED_APPOINTMENTS = "GET_REJECTED_APPOINTMENTS";

export const GET_PATIENTS = "GET_PATIENTS";

export const GET_ROOMS = "GET_ROOMS";
export const ADD_ROOM = "ADD_ROOM";
export const UPDATE_ROOM = "UPDATE_ROOM";
export const DELETE_ROOM = "DELETE_ROOM";

export const GET_STAFFS = "GET_STAFFS";
export const ADD_STAFFS = "ADD_STAFFS";
export const DELETE_STAFFS = "DELETE_STAFFS";
export const UPDATE_STAFFS = "UPDATE_STAFFS";

export const GET_EXPENSES = "GET_EXPENSES";
export const ADD_EXPENSE = "ADD_EXPENSE";

export const UPDATE_EXPENSE = "UPDATE_EXPENSE";
export const DELETE_EXPENSE = "DELETE_EXPENSE";

export const GET_BILLING_RECORDS = "GET_BILLING_RECORDS";
export const GET_BILL_DETAILS = "GET_BILL_DETAILS";

export const GET_SERVICES = "GET_SERVICES"

export const ADD_SERVICE = "ADD_SERVICE"
