export const GET_PATIENTS = "GET_PATIENTS";
export const GET_INPATIENTS = "GET_INPATIENTS";
export const GET_SURGERIES = "GET_SURGERIES";
export const GET_ROOMS = "GET_ROOMS";
export const GET_STATS = "GET_STATS";
export const GET_PATIENT_OVERVIEW = "GET_PATIENT_OVERVIEW";
export const GET_MOST_COMMON_DIAGNOSIS = "GET_MOST_COMMON_DIAGNOSIS";
export const GET_UPCOMING_EVENTS = "GET_UPCOMING_EVENTS";
export const GET_MONTHLY_EVENTS = "GET_MONTHLY_EVENTS";
export const CREATE_NEW_EVENT = "CREATE_NEW_EVENT";
export const GET_CRITICAL_PATIENTS = "GET_CRITICAL_PATIENTS";
export const GET_PATIENT_TREATMENT_PHASES = "GET_PATIENT_TREATMENT_PHASES";

export const GET_APPOINTMENTS = "GET_APPOINTMENTS";
export const GET_SCHEDULED_APPOINTMENTS = "GET_SCHEDULED_APPOINTMENTS";
export const GET_ONGOING_APPOINTMENTS = "GET_ONGOING_APPOINTMENTS";
export const GET_WAITING_APPOINTMENTS = "GET_WAITING_APPOINTMENTS";
export const GET_COMPLETED_APPOINTMENTS = "GET_COMPLETED_APPOINTMENTS";

export const GET_DOCTOR_REQUESTS = "GET_DOCTOR_REQUESTS";
export const CREATE_DOCTOR_REQUESTS = "CREATE_DOCTOR_REQUESTS";
export const GET_APPOINTMENT_REQUESTS = "GET_APPOINTMENT_REQUESTS";
export const APPROVE_APPOINTMENT = "APPROVE_APPOINTMENT";
export const REJECT_APPOINTMENT = "REJECT_APPOINTMENT";

export const GET_MEDICAL_PROCEDURE_STATS = "GET_MEDICAL_PROCEDURE_STATS";
export const GET_DOCTORS = "GET_DOCTORS";
export const GET_STAFF = "GET_STAFF";

export const GET_INVENTORY_DATA = "GET_INVENTORY_DATA";
export const GET_DOCTOR_NOTES = "GET_DOCTOR_NOTES";
export const CREATE_DOCTOR_NOTE = "CREATE_DOCTOR_NOTE";
export const EDIT_DOCTOR_NOTE = "EDIT_DOCTOR_NOTE";
export const DELETE_DOCTOR_NOTE = "DELETE_DOCTOR_NOTE";

export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const GET_APPOINTMENTS_BY_DATE = "GET_APPOINTMENTS_BY_DATE";
export const GET_APPOINTMENTS_OF_TODAY = "GET_APPOINTMENTS_OF_TODAY";
export const ADD_INVENTORY_ITEM = "ADD_INVENTORY_ITEM";

export const GET_INVENTORY = "GET_INVENTORY";
export const GENERATE_PRESCRIPTIONS_WITH_AI = "GENERATE_PRESCRIPTIONS_WITH_AI";
export const REMOVE_PRESCRIPTIONS_WITH_AI = "REMOVE_PRESCRIPTIONS_WITH_AI";
export const GET_APPOINTMENT_HISTORY = "GET_APPOINTMENT_HISTORY";
export const GET_ADMITTED_PATIENTS = "GET_ADMITTED_PATIENTS";
export const GET_PROGRESS_TRACKER = "GET_PROGRESS_TRACKER";
export const SUBMIT_CONSULTATION = "SUBMIT_CONSULTATION";
export const GET_ALL_DOCTORS = "GET_ALL_DOCTORS";
export const CREATE_ADMISSION_REQUEST = "CREATE_ADMISSION_REQUEST";
export const GET_APPROVED_ADMISSIONS = "GET_APPROVED_ADMISSIONS";
export const GET_ADMISSION_REQUESTS = "GET_ADMISSION_REQUESTS";
export const GET_ALL_USER_CONSULTATION_FORMS =
  "GET_ALL_USER_CONSULTATION_FORMS";
export const CREATE_NEW_CONSULTATION_FORM = "CREATE_NEW_CONSULTATION_FORM";

export const GET_PATIENTS_DEATILS = "GET_PATIENTS_DEATILS";
export const GET_PATIENTS_VITALS = "GET_PATIENTS_VITALS";
export const GET_ALL_DEPARTMENTS = "GET_ALL_DEPARTMENTS";
export const GET_PATIENT_HISTORY = "GET_PATIENT_HISTORY";
export const GET_PATIENT_MEDICAL_RECORDS = "GET_PATIENT_MEDICAL_RECORDS";
export const GET_PATIENT_BED_INFO = "GET_PATIENT_BED_INFO";
export const GET_ADMISSION_REQUESTS_TO_APPROVE =
  " GET_ADMISSION_REQUESTS_TO_APPROVE";

export const GET_AVAILABLE_BEDS = "GET_AVAILABLE_BEDS";
export const GET_AVAILABLE_ROOMS = "GET_AVAILABLE_ROOMS";
