export const GET_PATIENTS = "GET_PATIENTS";
export const GET_INPATIENTS = "GET_INPATIENTS";
export const GET_SURGERIES = "GET_SURGERIES";
export const GET_ROOMS = "GET_ROOMS";
export const GET_STATS = "GET_STATS";
export const GET_PATIENT_OVERVIEW = "GET_PATIENT_OVERVIEW";
export const GET_MOST_COMMON_DIAGNOSIS = "GET_MOST_COMMON_DIAGNOSIS";
export const GET_UPCOMING_EVENTS = "GET_UPCOMING_EVENTS";
export const GET_MONTHLY_EVENTS = "GET_MONTHLY_EVENTS";
export const CREATE_NEW_EVENT = "CREATE_NEW_EVENT";
export const GET_CRITICAL_PATIENTS = "GET_CRITICAL_PATIENTS";
export const GET_PATIENT_TREATMENT_PHASES = "GET_PATIENT_TREATMENT_PHASES";

export const GET_APPOINTMENTS = "GET_APPOINTMENTS";
export const GET_SCHEDULED_APPOINTMENTS = "GET_SCHEDULED_APPOINTMENTS";
export const GET_ONGOING_APPOINTMENTS = "GET_ONGOING_APPOINTMENTS";
export const GET_WAITING_APPOINTMENTS = "GET_WAITING_APPOINTMENTS";
export const GET_COMPLETED_APPOINTMENTS = "GET_COMPLETED_APPOINTMENTS";

export const GET_DOCTOR_REQUESTS = "GET_DOCTOR_REQUESTS";
export const CREATE_DOCTOR_REQUESTS = "CREATE_DOCTOR_REQUESTS";
export const GET_APPOINTMENT_REQUESTS = "GET_APPOINTMENT_REQUESTS";
export const APPROVE_APPOINTMENT = "APPROVE_APPOINTMENT";
export const REJECT_APPOINTMENT = "REJECT_APPOINTMENT";

export const GET_MEDICAL_PROCEDURE_STATS = "GET_MEDICAL_PROCEDURE_STATS";
export const GET_DOCTORS = "GET_DOCTORS";
export const GET_STAFF = "GET_STAFF";

export const GET_INVENTORY_DATA = "GET_INVENTORY_DATA";
export const GET_DOCTOR_NOTES = "GET_DOCTOR_NOTES";
export const CREATE_DOCTOR_NOTE = "CREATE_DOCTOR_NOTE";

export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const ADD_INVENTORY_ITEM = "ADD_INVENTORY_ITEM";

export const GET_INVENTORY = "GET_INVENTORY";
