export const patientData = [
  {
    id: "XXXXXXX",
    name: "Jatindra kaur",
    email: "jatindra@gmail.com",
    phoneNo: "1234567890",
    typeVisit: "Walk in",
    branch: "Cardiology",
    date: "08-1-2025",
    booking: "Active",
    bed: "C-108",
    condition: "Valve Repair",
    doctor: "Dr. Patel",
    status: "Critical",
    status2: "Completed",

    surgeryType: "Arrythmia",
  },
  {
    id: "XXXXXXX",
    name: "Amit Tripathi",
    email: "amittripathi@gmail.com",
    bed: "C-109",
    condition: "Heart Failure",
    doctor: "Dr. Patel",
    status: "Stable",
    status2: "Scheduled",

    phoneNo: "1234567890",
    typeVisit: "Walk in",
    branch: "Cardiology",
    date: "08-1-2025",
    booking: "Inactive",
    surgeryType: "Coronary Bypass",
  },
  {
    id: "XXXXXXX",
    name: "Arvind Sharma",
    email: "arvind.sharma@gmail.com",
    bed: "C-108",
    condition: "Arrhythmia",
    doctor: "Dr. Patel",
    status: "Stable",
    status2: "Cancelled",

    phoneNo: "1234567890",
    typeVisit: "Walk in",
    branch: "Cardiology",
    date: "08-1-2025",
    booking: "Active",
    surgeryType: "Valve Repair",
  },
  {
    id: "XXXXXXX",
    name: "Kumari Sneha",
    email: "kumari.sneha@gmail.com",
    bed: "D-108",
    condition: "Angioplasty",
    doctor: "Dr. Patel",
    status: "Stable",
    status2: "Cancelled",
    phoneNo: "1234567890",
    typeVisit: "Walk in",
    branch: "Cardiology",
    date: "08-1-2025",
    booking: "Inactive",
    surgeryType: "Valve Replacement",
  },
  {
    id: "XXXXXXX",
    name: "Aditya Soni",
    email: "aditya.soni@gmail.com",
    bed: "C-108",
    condition: "Stent Replacement",
    doctor: "Dr. Patel",
    status: "Stable",
    status2: "Completed",

    phoneNo: "1234567890",
    typeVisit: "Walk in",
    branch: "Cardiology",
    date: "08-1-2025",
    booking: "Active",
    surgeryType: "Pacemaker Implant",
  },
  {
    id: "XXXXXXX",
    name: "Khushi Saini",
    email: "khushi.saini@gmail.com",
    bed: "C-108",
    condition: "Angioplasty",
    doctor: "Dr. Patel",
    status: "Stable",
    status2: "Scheduled",

    phoneNo: "1234567890",
    typeVisit: "Walk in",
    branch: "Cardiology",
    date: "08-1-2025",
    booking: "Active",
    surgeryType: "Angloplasty",
  },
  {
    id: "XXXXXXX",
    name: "Yash Sharma",
    email: "yash.sharma@gmail.com",
    bed: "C-108",
    condition: "Heart Failure",
    doctor: "Dr. Patel",
    status: "Critical",
    status2: "Scheduled",
    phoneNo: "1234567890",
    typeVisit: "Walk in",
    branch: "Cardiology",
    date: "08-1-2025",
    booking: "Active",
    surgeryType: "Valve Repair",
  },
  {
    id: "XXXXXXX",
    name: "Ayush Trivedi",
    email: "ayush.trivedi@gmail.com",
    bed: "C-108",
    condition: "Valve Repair",
    doctor: "Dr. Patel",
    status: "Stable",
    status2: "Completed",

    phoneNo: "1234567890",
    typeVisit: "Walk in",
    branch: "Cardiology",
    date: "08-1-2025",
    booking: "Active",
    surgeryType: "Angloplasty",
  },
];
