export const GET_RECEPTIONIST_OVERVIEW_SUCCESS =
  "GET_RECEPTIONIST_OVERVIEW_SUCCESS";

export const GET_PATIENTS = "GET_PATIENTS";
export const GET_DOCTORS = "GET_DOCTORS";
export const GET_STAFFS = "GET_STAFFS";
export const GET_ROOMS = "GET_ROOMS";
export const ADD_ROOM = "ADD_ROOM";

export const GET_ALL_DEPARTMENTS = "GET_ALL_DEPARTMENTS";

export const GET_DEPARTMENT_BY_ID = "GET_DEPARTMENT_BY_ID";

export const BOOK_APPOINTMENT = "BOOK_APPOINTMENT";

export const GET_APPOINTMENTS = "GET_APPOINTMENTS";

export const GET_APPOINTMENT_REQUESTS = "GET_APPOINTMENT_REQUESTS";

export const GET_BILLS = "GET_BILLS";
export const GET_BILL_BY_ID = "GET_BILL_BY_ID";

export const GET_RECEPTIONIST_PATIENTS_SUCCESS =
  "GET_RECEPTIONIST_PATIENTS_SUCCESS";
