export const GET_RECEPTIONIST_OVERVIEW_REQUEST = 'GET_RECEPTIONIST_OVERVIEW_REQUEST'
export const GET_RECEPTIONIST_OVERVIEW_SUCCESS = 'GET_RECEPTIONIST_OVERVIEW_SUCCESS'
export const GET_RECEPTIONIST_OVERVIEW_FAILURE = 'GET_RECEPTIONIST_OVERVIEW_FAILURE'

export const GET_PATIENTS = 'GET_PATIENTS';
export const GET_DOCTORS = 'GET_DOCTORS';
export const GET_STAFFS = 'GET_STAFFS';
export const GET_ROOMS = 'GET_ROOMS';

export const GET_ALL_DEPARTMENTS = 'GET_ALL_DEPARTMENTS'

export const GET_DEPARTMENT_BY_ID = 'GET_DEPARTMENT_BY_ID'

export const GET_RECEPTIONIST_PATIENTS_REQUEST = 'GET_RECEPTIONIST_PATIENTS_REQUEST'
export const GET_RECEPTIONIST_PATIENTS_SUCCESS = 'GET_RECEPTIONIST_PATIENTS_SUCCESS'
export const GET_RECEPTIONIST_PATIENTS_FAILURE = 'GET_RECEPTIONIST_PATIENTS_FAILURE'