export const GET_RECEPTIONIST_OVERVIEW_SUCCESS =
  "GET_RECEPTIONIST_OVERVIEW_SUCCESS";

export const GET_PATIENTS = "GET_PATIENTS";
export const GET_FILTERED_PATIENTS = "GET_FILTERED_PATIENTS";
export const GET_INPATIENTS = "GET_INPATIENTS";
export const GET_FILTERED_INPATIENTS = "GET_FILTERED_INPATIENTS";
export const GET_PATIENT_DETAILS = "GET_PATIENT_DETAILS";
export const GET_DOCTORS = "GET_DOCTORS";
export const GET_STAFFS = "GET_STAFFS";
export const GET_ROOMS = "GET_ROOMS";
export const GET_FILTERED_ROOMS = "GET_FILTERED_ROOMS";
export const ADD_ROOM = "ADD_ROOM";
export const UPDATE_ROOM = "UPDATE_ROOM";
export const DELETE_ROOM = "DELETE_ROOM";
export const GET_FILTERED_DOCTORS = "GET_FILTERED_DOCTORS";

export const GET_ALL_DEPARTMENTS = "GET_ALL_DEPARTMENTS";

export const GET_DEPARTMENT_BY_ID = "GET_DEPARTMENT_BY_ID";
export const GET_SERVICES_BY_DEPARTMENT_ID = "GET_SERVICES_BY_DEPARTMENT_ID";

export const BOOK_APPOINTMENT = "BOOK_APPOINTMENT";
export const REMOVE_BOOK_APPOINTMENT_DATA = "REMOVE_BOOK_APPOINTMENT_DATA";

export const GET_APPOINTMENTS = "GET_APPOINTMENTS";

export const GET_FILTERED_APPOINTMENTS = "GET_FILTERED_APPOINTMENTS";

export const GET_SCHEDULED_APPOINTMENTS = "GET_SCHEDULED_APPOINTMENTS";
export const GET_ONGOING_APPOINTMENTS = "GET_ONGOING_APPOINTMENTS";
export const GET_WAITING_APPOINTMENTS = "GET_WAITING_APPOINTMENTS";
export const GET_COMPLETED_APPOINTMENTS = "GET_COMPLETED_APPOINTMENTS";

export const GET_APPOINTMENT_REQUESTS = "GET_APPOINTMENT_REQUESTS";

export const ACCEPT_APPOINTMENT_REQUESTS = "ACCEPT_APPOINTMENT_REQUESTS";
export const REJECT_APPOINTMENT_REQUESTS = "REJECT_APPOINTMENT_REQUESTS";

export const GET_BILLS = "GET_BILLS";
export const GET_BILL_BY_ID = "GET_BILL_BY_ID";

export const GET_RECEPTIONIST_PATIENTS_SUCCESS =
  "GET_RECEPTIONIST_PATIENTS_SUCCESS";

export const GET_DOCTORS_BY_DEPARTMENT = "GET_DOCTORS_BY_DEPARTMENT";
export const GET_PROGRESS_TRACKER = "GET_PROGRESS_TRACKER";
export const GET_PATIENT_BILLS = "GET_PATIENT_BILLS";
export const START_CONSULTATION = "START_CONSULTATION";
export const SUBMIT_CONSULTATION = "SUBMIT_CONSULTATION";
export const GET_PATIENT_FILES = "GET_PATIENT_FILES";
export const UPLOAD_PATIENT_FILE = "UPLOAD_PATIENT_FILE";
export const DELETE_PATIENT_FILE = "DELETE_PATIENT_FILE";

export const SET_LOADING_APPOINTMENTS = "SET_LOADING_APPOINTMENTS";

export const ADD_PAYMENT_TO_BILL = "ADD_PAYMENT_TO_BILL";
export const GET_BILL_DETAILS = "GET_BILL_DETAILS";
export const EDIT_BILL = "EDIT_BILL";
export const ADD_TO_BILL = "ADD_TO_BILL";

export const UPDATE_PATIENT = "UPDATE_PATIENT";
export const LOADING_FILTERED_INPATIENTS = "LOADING_FILTERED_INPATIENTS";
export const LOADING_PATIENTS = "LOADING_PATIENTS";
export const LOADING_DOCTORS = "LOADING_DOCTORS";
